// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gems/metadata.proto

package gems;

public final class MetaDataProtos {
  private MetaDataProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MetaDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // repeated .tutorial.MetaData.GossipEntry GossipList = 2;
    java.util.List<gems.MetaDataProtos.MetaData.GossipEntry> 
        getGossipListList();
    gems.MetaDataProtos.MetaData.GossipEntry getGossipList(int index);
    int getGossipListCount();
    java.util.List<? extends gems.MetaDataProtos.MetaData.GossipEntryOrBuilder> 
        getGossipListOrBuilderList();
    gems.MetaDataProtos.MetaData.GossipEntryOrBuilder getGossipListOrBuilder(
        int index);
    
    // repeated .tutorial.MetaData.SuspectEntry SuspectMatrix = 3;
    java.util.List<gems.MetaDataProtos.MetaData.SuspectEntry> 
        getSuspectMatrixList();
    gems.MetaDataProtos.MetaData.SuspectEntry getSuspectMatrix(int index);
    int getSuspectMatrixCount();
    java.util.List<? extends gems.MetaDataProtos.MetaData.SuspectEntryOrBuilder> 
        getSuspectMatrixOrBuilderList();
    gems.MetaDataProtos.MetaData.SuspectEntryOrBuilder getSuspectMatrixOrBuilder(
        int index);
  }
  public static final class MetaData extends
      com.google.protobuf.GeneratedMessage
      implements MetaDataOrBuilder {
    // Use MetaData.newBuilder() to construct.
    private MetaData(Builder builder) {
      super(builder);
    }
    private MetaData(boolean noInit) {}
    
    private static final MetaData defaultInstance;
    public static MetaData getDefaultInstance() {
      return defaultInstance;
    }
    
    public MetaData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gems.MetaDataProtos.internal_static_tutorial_MetaData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gems.MetaDataProtos.internal_static_tutorial_MetaData_fieldAccessorTable;
    }
    
    public interface GossipEntryOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required int32 id = 1;
      boolean hasId();
      int getId();
      
      // required int32 heartbeat = 2;
      boolean hasHeartbeat();
      int getHeartbeat();
    }
    public static final class GossipEntry extends
        com.google.protobuf.GeneratedMessage
        implements GossipEntryOrBuilder {
      // Use GossipEntry.newBuilder() to construct.
      private GossipEntry(Builder builder) {
        super(builder);
      }
      private GossipEntry(boolean noInit) {}
      
      private static final GossipEntry defaultInstance;
      public static GossipEntry getDefaultInstance() {
        return defaultInstance;
      }
      
      public GossipEntry getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gems.MetaDataProtos.internal_static_tutorial_MetaData_GossipEntry_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gems.MetaDataProtos.internal_static_tutorial_MetaData_GossipEntry_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required int32 id = 1;
      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      
      // required int32 heartbeat = 2;
      public static final int HEARTBEAT_FIELD_NUMBER = 2;
      private int heartbeat_;
      public boolean hasHeartbeat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getHeartbeat() {
        return heartbeat_;
      }
      
      private void initFields() {
        id_ = 0;
        heartbeat_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasHeartbeat()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, heartbeat_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, heartbeat_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static gems.MetaDataProtos.MetaData.GossipEntry parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static gems.MetaDataProtos.MetaData.GossipEntry parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static gems.MetaDataProtos.MetaData.GossipEntry parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static gems.MetaDataProtos.MetaData.GossipEntry parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static gems.MetaDataProtos.MetaData.GossipEntry parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static gems.MetaDataProtos.MetaData.GossipEntry parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static gems.MetaDataProtos.MetaData.GossipEntry parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static gems.MetaDataProtos.MetaData.GossipEntry parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static gems.MetaDataProtos.MetaData.GossipEntry parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static gems.MetaDataProtos.MetaData.GossipEntry parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(gems.MetaDataProtos.MetaData.GossipEntry prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements gems.MetaDataProtos.MetaData.GossipEntryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return gems.MetaDataProtos.internal_static_tutorial_MetaData_GossipEntry_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return gems.MetaDataProtos.internal_static_tutorial_MetaData_GossipEntry_fieldAccessorTable;
        }
        
        // Construct using gems.MetaDataProtos.MetaData.GossipEntry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          id_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          heartbeat_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return gems.MetaDataProtos.MetaData.GossipEntry.getDescriptor();
        }
        
        public gems.MetaDataProtos.MetaData.GossipEntry getDefaultInstanceForType() {
          return gems.MetaDataProtos.MetaData.GossipEntry.getDefaultInstance();
        }
        
        public gems.MetaDataProtos.MetaData.GossipEntry build() {
          gems.MetaDataProtos.MetaData.GossipEntry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private gems.MetaDataProtos.MetaData.GossipEntry buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          gems.MetaDataProtos.MetaData.GossipEntry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public gems.MetaDataProtos.MetaData.GossipEntry buildPartial() {
          gems.MetaDataProtos.MetaData.GossipEntry result = new gems.MetaDataProtos.MetaData.GossipEntry(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.heartbeat_ = heartbeat_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof gems.MetaDataProtos.MetaData.GossipEntry) {
            return mergeFrom((gems.MetaDataProtos.MetaData.GossipEntry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(gems.MetaDataProtos.MetaData.GossipEntry other) {
          if (other == gems.MetaDataProtos.MetaData.GossipEntry.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasHeartbeat()) {
            setHeartbeat(other.getHeartbeat());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasId()) {
            
            return false;
          }
          if (!hasHeartbeat()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                id_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                heartbeat_ = input.readInt32();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required int32 id = 1;
        private int id_ ;
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public int getId() {
          return id_;
        }
        public Builder setId(int value) {
          bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0;
          onChanged();
          return this;
        }
        
        // required int32 heartbeat = 2;
        private int heartbeat_ ;
        public boolean hasHeartbeat() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public int getHeartbeat() {
          return heartbeat_;
        }
        public Builder setHeartbeat(int value) {
          bitField0_ |= 0x00000002;
          heartbeat_ = value;
          onChanged();
          return this;
        }
        public Builder clearHeartbeat() {
          bitField0_ = (bitField0_ & ~0x00000002);
          heartbeat_ = 0;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:tutorial.MetaData.GossipEntry)
      }
      
      static {
        defaultInstance = new GossipEntry(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:tutorial.MetaData.GossipEntry)
    }
    
    public interface SuspectEntryOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required int32 rowIndex = 1;
      boolean hasRowIndex();
      int getRowIndex();
      
      // repeated .tutorial.MetaData.SuspectEntry.SuspectRowEntry SuspectRow = 2;
      java.util.List<gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry> 
          getSuspectRowList();
      gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry getSuspectRow(int index);
      int getSuspectRowCount();
      java.util.List<? extends gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntryOrBuilder> 
          getSuspectRowOrBuilderList();
      gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntryOrBuilder getSuspectRowOrBuilder(
          int index);
    }
    public static final class SuspectEntry extends
        com.google.protobuf.GeneratedMessage
        implements SuspectEntryOrBuilder {
      // Use SuspectEntry.newBuilder() to construct.
      private SuspectEntry(Builder builder) {
        super(builder);
      }
      private SuspectEntry(boolean noInit) {}
      
      private static final SuspectEntry defaultInstance;
      public static SuspectEntry getDefaultInstance() {
        return defaultInstance;
      }
      
      public SuspectEntry getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gems.MetaDataProtos.internal_static_tutorial_MetaData_SuspectEntry_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gems.MetaDataProtos.internal_static_tutorial_MetaData_SuspectEntry_fieldAccessorTable;
      }
      
      public interface SuspectRowEntryOrBuilder
          extends com.google.protobuf.MessageOrBuilder {
        
        // required int32 colindex = 1;
        boolean hasColindex();
        int getColindex();
        
        // required int32 value = 2;
        boolean hasValue();
        int getValue();
      }
      public static final class SuspectRowEntry extends
          com.google.protobuf.GeneratedMessage
          implements SuspectRowEntryOrBuilder {
        // Use SuspectRowEntry.newBuilder() to construct.
        private SuspectRowEntry(Builder builder) {
          super(builder);
        }
        private SuspectRowEntry(boolean noInit) {}
        
        private static final SuspectRowEntry defaultInstance;
        public static SuspectRowEntry getDefaultInstance() {
          return defaultInstance;
        }
        
        public SuspectRowEntry getDefaultInstanceForType() {
          return defaultInstance;
        }
        
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return gems.MetaDataProtos.internal_static_tutorial_MetaData_SuspectEntry_SuspectRowEntry_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return gems.MetaDataProtos.internal_static_tutorial_MetaData_SuspectEntry_SuspectRowEntry_fieldAccessorTable;
        }
        
        private int bitField0_;
        // required int32 colindex = 1;
        public static final int COLINDEX_FIELD_NUMBER = 1;
        private int colindex_;
        public boolean hasColindex() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public int getColindex() {
          return colindex_;
        }
        
        // required int32 value = 2;
        public static final int VALUE_FIELD_NUMBER = 2;
        private int value_;
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public int getValue() {
          return value_;
        }
        
        private void initFields() {
          colindex_ = 0;
          value_ = 0;
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized != -1) return isInitialized == 1;
          
          if (!hasColindex()) {
            memoizedIsInitialized = 0;
            return false;
          }
          if (!hasValue()) {
            memoizedIsInitialized = 0;
            return false;
          }
          memoizedIsInitialized = 1;
          return true;
        }
        
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          getSerializedSize();
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            output.writeInt32(1, colindex_);
          }
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            output.writeInt32(2, value_);
          }
          getUnknownFields().writeTo(output);
        }
        
        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
          int size = memoizedSerializedSize;
          if (size != -1) return size;
        
          size = 0;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(1, colindex_);
          }
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(2, value_);
          }
          size += getUnknownFields().getSerializedSize();
          memoizedSerializedSize = size;
          return size;
        }
        
        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
          return super.writeReplace();
        }
        
        public static gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data).buildParsed();
        }
        public static gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data, extensionRegistry)
                   .buildParsed();
        }
        public static gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data).buildParsed();
        }
        public static gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data, extensionRegistry)
                   .buildParsed();
        }
        public static gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input).buildParsed();
        }
        public static gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input, extensionRegistry)
                   .buildParsed();
        }
        public static gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          Builder builder = newBuilder();
          if (builder.mergeDelimitedFrom(input)) {
            return builder.buildParsed();
          } else {
            return null;
          }
        }
        public static gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Builder builder = newBuilder();
          if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
            return builder.buildParsed();
          } else {
            return null;
          }
        }
        public static gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input).buildParsed();
        }
        public static gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input, extensionRegistry)
                   .buildParsed();
        }
        
        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry prototype) {
          return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }
        
        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          Builder builder = new Builder(parent);
          return builder;
        }
        public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder>
           implements gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntryOrBuilder {
          public static final com.google.protobuf.Descriptors.Descriptor
              getDescriptor() {
            return gems.MetaDataProtos.internal_static_tutorial_MetaData_SuspectEntry_SuspectRowEntry_descriptor;
          }
          
          protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
              internalGetFieldAccessorTable() {
            return gems.MetaDataProtos.internal_static_tutorial_MetaData_SuspectEntry_SuspectRowEntry_fieldAccessorTable;
          }
          
          // Construct using gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.newBuilder()
          private Builder() {
            maybeForceBuilderInitialization();
          }
          
          private Builder(BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
          }
          private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            }
          }
          private static Builder create() {
            return new Builder();
          }
          
          public Builder clear() {
            super.clear();
            colindex_ = 0;
            bitField0_ = (bitField0_ & ~0x00000001);
            value_ = 0;
            bitField0_ = (bitField0_ & ~0x00000002);
            return this;
          }
          
          public Builder clone() {
            return create().mergeFrom(buildPartial());
          }
          
          public com.google.protobuf.Descriptors.Descriptor
              getDescriptorForType() {
            return gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.getDescriptor();
          }
          
          public gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry getDefaultInstanceForType() {
            return gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.getDefaultInstance();
          }
          
          public gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry build() {
            gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return result;
          }
          
          private gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry buildParsed()
              throws com.google.protobuf.InvalidProtocolBufferException {
            gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(
                result).asInvalidProtocolBufferException();
            }
            return result;
          }
          
          public gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry buildPartial() {
            gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry result = new gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
              to_bitField0_ |= 0x00000001;
            }
            result.colindex_ = colindex_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
              to_bitField0_ |= 0x00000002;
            }
            result.value_ = value_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
          }
          
          public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry) {
              return mergeFrom((gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry)other);
            } else {
              super.mergeFrom(other);
              return this;
            }
          }
          
          public Builder mergeFrom(gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry other) {
            if (other == gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.getDefaultInstance()) return this;
            if (other.hasColindex()) {
              setColindex(other.getColindex());
            }
            if (other.hasValue()) {
              setValue(other.getValue());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            return this;
          }
          
          public final boolean isInitialized() {
            if (!hasColindex()) {
              
              return false;
            }
            if (!hasValue()) {
              
              return false;
            }
            return true;
          }
          
          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder(
                this.getUnknownFields());
            while (true) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                default: {
                  if (!parseUnknownField(input, unknownFields,
                                         extensionRegistry, tag)) {
                    this.setUnknownFields(unknownFields.build());
                    onChanged();
                    return this;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  colindex_ = input.readInt32();
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  value_ = input.readInt32();
                  break;
                }
              }
            }
          }
          
          private int bitField0_;
          
          // required int32 colindex = 1;
          private int colindex_ ;
          public boolean hasColindex() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
          }
          public int getColindex() {
            return colindex_;
          }
          public Builder setColindex(int value) {
            bitField0_ |= 0x00000001;
            colindex_ = value;
            onChanged();
            return this;
          }
          public Builder clearColindex() {
            bitField0_ = (bitField0_ & ~0x00000001);
            colindex_ = 0;
            onChanged();
            return this;
          }
          
          // required int32 value = 2;
          private int value_ ;
          public boolean hasValue() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
          }
          public int getValue() {
            return value_;
          }
          public Builder setValue(int value) {
            bitField0_ |= 0x00000002;
            value_ = value;
            onChanged();
            return this;
          }
          public Builder clearValue() {
            bitField0_ = (bitField0_ & ~0x00000002);
            value_ = 0;
            onChanged();
            return this;
          }
          
          // @@protoc_insertion_point(builder_scope:tutorial.MetaData.SuspectEntry.SuspectRowEntry)
        }
        
        static {
          defaultInstance = new SuspectRowEntry(true);
          defaultInstance.initFields();
        }
        
        // @@protoc_insertion_point(class_scope:tutorial.MetaData.SuspectEntry.SuspectRowEntry)
      }
      
      private int bitField0_;
      // required int32 rowIndex = 1;
      public static final int ROWINDEX_FIELD_NUMBER = 1;
      private int rowIndex_;
      public boolean hasRowIndex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getRowIndex() {
        return rowIndex_;
      }
      
      // repeated .tutorial.MetaData.SuspectEntry.SuspectRowEntry SuspectRow = 2;
      public static final int SUSPECTROW_FIELD_NUMBER = 2;
      private java.util.List<gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry> suspectRow_;
      public java.util.List<gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry> getSuspectRowList() {
        return suspectRow_;
      }
      public java.util.List<? extends gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntryOrBuilder> 
          getSuspectRowOrBuilderList() {
        return suspectRow_;
      }
      public int getSuspectRowCount() {
        return suspectRow_.size();
      }
      public gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry getSuspectRow(int index) {
        return suspectRow_.get(index);
      }
      public gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntryOrBuilder getSuspectRowOrBuilder(
          int index) {
        return suspectRow_.get(index);
      }
      
      private void initFields() {
        rowIndex_ = 0;
        suspectRow_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasRowIndex()) {
          memoizedIsInitialized = 0;
          return false;
        }
        for (int i = 0; i < getSuspectRowCount(); i++) {
          if (!getSuspectRow(i).isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, rowIndex_);
        }
        for (int i = 0; i < suspectRow_.size(); i++) {
          output.writeMessage(2, suspectRow_.get(i));
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, rowIndex_);
        }
        for (int i = 0; i < suspectRow_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, suspectRow_.get(i));
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static gems.MetaDataProtos.MetaData.SuspectEntry parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static gems.MetaDataProtos.MetaData.SuspectEntry parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static gems.MetaDataProtos.MetaData.SuspectEntry parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static gems.MetaDataProtos.MetaData.SuspectEntry parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static gems.MetaDataProtos.MetaData.SuspectEntry parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static gems.MetaDataProtos.MetaData.SuspectEntry parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static gems.MetaDataProtos.MetaData.SuspectEntry parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static gems.MetaDataProtos.MetaData.SuspectEntry parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static gems.MetaDataProtos.MetaData.SuspectEntry parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static gems.MetaDataProtos.MetaData.SuspectEntry parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(gems.MetaDataProtos.MetaData.SuspectEntry prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements gems.MetaDataProtos.MetaData.SuspectEntryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return gems.MetaDataProtos.internal_static_tutorial_MetaData_SuspectEntry_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return gems.MetaDataProtos.internal_static_tutorial_MetaData_SuspectEntry_fieldAccessorTable;
        }
        
        // Construct using gems.MetaDataProtos.MetaData.SuspectEntry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getSuspectRowFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          rowIndex_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          if (suspectRowBuilder_ == null) {
            suspectRow_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            suspectRowBuilder_.clear();
          }
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return gems.MetaDataProtos.MetaData.SuspectEntry.getDescriptor();
        }
        
        public gems.MetaDataProtos.MetaData.SuspectEntry getDefaultInstanceForType() {
          return gems.MetaDataProtos.MetaData.SuspectEntry.getDefaultInstance();
        }
        
        public gems.MetaDataProtos.MetaData.SuspectEntry build() {
          gems.MetaDataProtos.MetaData.SuspectEntry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private gems.MetaDataProtos.MetaData.SuspectEntry buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          gems.MetaDataProtos.MetaData.SuspectEntry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public gems.MetaDataProtos.MetaData.SuspectEntry buildPartial() {
          gems.MetaDataProtos.MetaData.SuspectEntry result = new gems.MetaDataProtos.MetaData.SuspectEntry(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.rowIndex_ = rowIndex_;
          if (suspectRowBuilder_ == null) {
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              suspectRow_ = java.util.Collections.unmodifiableList(suspectRow_);
              bitField0_ = (bitField0_ & ~0x00000002);
            }
            result.suspectRow_ = suspectRow_;
          } else {
            result.suspectRow_ = suspectRowBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof gems.MetaDataProtos.MetaData.SuspectEntry) {
            return mergeFrom((gems.MetaDataProtos.MetaData.SuspectEntry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(gems.MetaDataProtos.MetaData.SuspectEntry other) {
          if (other == gems.MetaDataProtos.MetaData.SuspectEntry.getDefaultInstance()) return this;
          if (other.hasRowIndex()) {
            setRowIndex(other.getRowIndex());
          }
          if (suspectRowBuilder_ == null) {
            if (!other.suspectRow_.isEmpty()) {
              if (suspectRow_.isEmpty()) {
                suspectRow_ = other.suspectRow_;
                bitField0_ = (bitField0_ & ~0x00000002);
              } else {
                ensureSuspectRowIsMutable();
                suspectRow_.addAll(other.suspectRow_);
              }
              onChanged();
            }
          } else {
            if (!other.suspectRow_.isEmpty()) {
              if (suspectRowBuilder_.isEmpty()) {
                suspectRowBuilder_.dispose();
                suspectRowBuilder_ = null;
                suspectRow_ = other.suspectRow_;
                bitField0_ = (bitField0_ & ~0x00000002);
                suspectRowBuilder_ = 
                  com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                     getSuspectRowFieldBuilder() : null;
              } else {
                suspectRowBuilder_.addAllMessages(other.suspectRow_);
              }
            }
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasRowIndex()) {
            
            return false;
          }
          for (int i = 0; i < getSuspectRowCount(); i++) {
            if (!getSuspectRow(i).isInitialized()) {
              
              return false;
            }
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                rowIndex_ = input.readInt32();
                break;
              }
              case 18: {
                gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.Builder subBuilder = gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.newBuilder();
                input.readMessage(subBuilder, extensionRegistry);
                addSuspectRow(subBuilder.buildPartial());
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required int32 rowIndex = 1;
        private int rowIndex_ ;
        public boolean hasRowIndex() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public int getRowIndex() {
          return rowIndex_;
        }
        public Builder setRowIndex(int value) {
          bitField0_ |= 0x00000001;
          rowIndex_ = value;
          onChanged();
          return this;
        }
        public Builder clearRowIndex() {
          bitField0_ = (bitField0_ & ~0x00000001);
          rowIndex_ = 0;
          onChanged();
          return this;
        }
        
        // repeated .tutorial.MetaData.SuspectEntry.SuspectRowEntry SuspectRow = 2;
        private java.util.List<gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry> suspectRow_ =
          java.util.Collections.emptyList();
        private void ensureSuspectRowIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            suspectRow_ = new java.util.ArrayList<gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry>(suspectRow_);
            bitField0_ |= 0x00000002;
           }
        }
        
        private com.google.protobuf.RepeatedFieldBuilder<
            gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry, gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.Builder, gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntryOrBuilder> suspectRowBuilder_;
        
        public java.util.List<gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry> getSuspectRowList() {
          if (suspectRowBuilder_ == null) {
            return java.util.Collections.unmodifiableList(suspectRow_);
          } else {
            return suspectRowBuilder_.getMessageList();
          }
        }
        public int getSuspectRowCount() {
          if (suspectRowBuilder_ == null) {
            return suspectRow_.size();
          } else {
            return suspectRowBuilder_.getCount();
          }
        }
        public gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry getSuspectRow(int index) {
          if (suspectRowBuilder_ == null) {
            return suspectRow_.get(index);
          } else {
            return suspectRowBuilder_.getMessage(index);
          }
        }
        public Builder setSuspectRow(
            int index, gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry value) {
          if (suspectRowBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureSuspectRowIsMutable();
            suspectRow_.set(index, value);
            onChanged();
          } else {
            suspectRowBuilder_.setMessage(index, value);
          }
          return this;
        }
        public Builder setSuspectRow(
            int index, gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.Builder builderForValue) {
          if (suspectRowBuilder_ == null) {
            ensureSuspectRowIsMutable();
            suspectRow_.set(index, builderForValue.build());
            onChanged();
          } else {
            suspectRowBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        public Builder addSuspectRow(gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry value) {
          if (suspectRowBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureSuspectRowIsMutable();
            suspectRow_.add(value);
            onChanged();
          } else {
            suspectRowBuilder_.addMessage(value);
          }
          return this;
        }
        public Builder addSuspectRow(
            int index, gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry value) {
          if (suspectRowBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureSuspectRowIsMutable();
            suspectRow_.add(index, value);
            onChanged();
          } else {
            suspectRowBuilder_.addMessage(index, value);
          }
          return this;
        }
        public Builder addSuspectRow(
            gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.Builder builderForValue) {
          if (suspectRowBuilder_ == null) {
            ensureSuspectRowIsMutable();
            suspectRow_.add(builderForValue.build());
            onChanged();
          } else {
            suspectRowBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        public Builder addSuspectRow(
            int index, gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.Builder builderForValue) {
          if (suspectRowBuilder_ == null) {
            ensureSuspectRowIsMutable();
            suspectRow_.add(index, builderForValue.build());
            onChanged();
          } else {
            suspectRowBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        public Builder addAllSuspectRow(
            java.lang.Iterable<? extends gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry> values) {
          if (suspectRowBuilder_ == null) {
            ensureSuspectRowIsMutable();
            super.addAll(values, suspectRow_);
            onChanged();
          } else {
            suspectRowBuilder_.addAllMessages(values);
          }
          return this;
        }
        public Builder clearSuspectRow() {
          if (suspectRowBuilder_ == null) {
            suspectRow_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
          } else {
            suspectRowBuilder_.clear();
          }
          return this;
        }
        public Builder removeSuspectRow(int index) {
          if (suspectRowBuilder_ == null) {
            ensureSuspectRowIsMutable();
            suspectRow_.remove(index);
            onChanged();
          } else {
            suspectRowBuilder_.remove(index);
          }
          return this;
        }
        public gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.Builder getSuspectRowBuilder(
            int index) {
          return getSuspectRowFieldBuilder().getBuilder(index);
        }
        public gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntryOrBuilder getSuspectRowOrBuilder(
            int index) {
          if (suspectRowBuilder_ == null) {
            return suspectRow_.get(index);  } else {
            return suspectRowBuilder_.getMessageOrBuilder(index);
          }
        }
        public java.util.List<? extends gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntryOrBuilder> 
             getSuspectRowOrBuilderList() {
          if (suspectRowBuilder_ != null) {
            return suspectRowBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(suspectRow_);
          }
        }
        public gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.Builder addSuspectRowBuilder() {
          return getSuspectRowFieldBuilder().addBuilder(
              gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.getDefaultInstance());
        }
        public gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.Builder addSuspectRowBuilder(
            int index) {
          return getSuspectRowFieldBuilder().addBuilder(
              index, gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.getDefaultInstance());
        }
        public java.util.List<gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.Builder> 
             getSuspectRowBuilderList() {
          return getSuspectRowFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilder<
            gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry, gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.Builder, gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntryOrBuilder> 
            getSuspectRowFieldBuilder() {
          if (suspectRowBuilder_ == null) {
            suspectRowBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry, gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.Builder, gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntryOrBuilder>(
                    suspectRow_,
                    ((bitField0_ & 0x00000002) == 0x00000002),
                    getParentForChildren(),
                    isClean());
            suspectRow_ = null;
          }
          return suspectRowBuilder_;
        }
        
        // @@protoc_insertion_point(builder_scope:tutorial.MetaData.SuspectEntry)
      }
      
      static {
        defaultInstance = new SuspectEntry(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:tutorial.MetaData.SuspectEntry)
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // repeated .tutorial.MetaData.GossipEntry GossipList = 2;
    public static final int GOSSIPLIST_FIELD_NUMBER = 2;
    private java.util.List<gems.MetaDataProtos.MetaData.GossipEntry> gossipList_;
    public java.util.List<gems.MetaDataProtos.MetaData.GossipEntry> getGossipListList() {
      return gossipList_;
    }
    public java.util.List<? extends gems.MetaDataProtos.MetaData.GossipEntryOrBuilder> 
        getGossipListOrBuilderList() {
      return gossipList_;
    }
    public int getGossipListCount() {
      return gossipList_.size();
    }
    public gems.MetaDataProtos.MetaData.GossipEntry getGossipList(int index) {
      return gossipList_.get(index);
    }
    public gems.MetaDataProtos.MetaData.GossipEntryOrBuilder getGossipListOrBuilder(
        int index) {
      return gossipList_.get(index);
    }
    
    // repeated .tutorial.MetaData.SuspectEntry SuspectMatrix = 3;
    public static final int SUSPECTMATRIX_FIELD_NUMBER = 3;
    private java.util.List<gems.MetaDataProtos.MetaData.SuspectEntry> suspectMatrix_;
    public java.util.List<gems.MetaDataProtos.MetaData.SuspectEntry> getSuspectMatrixList() {
      return suspectMatrix_;
    }
    public java.util.List<? extends gems.MetaDataProtos.MetaData.SuspectEntryOrBuilder> 
        getSuspectMatrixOrBuilderList() {
      return suspectMatrix_;
    }
    public int getSuspectMatrixCount() {
      return suspectMatrix_.size();
    }
    public gems.MetaDataProtos.MetaData.SuspectEntry getSuspectMatrix(int index) {
      return suspectMatrix_.get(index);
    }
    public gems.MetaDataProtos.MetaData.SuspectEntryOrBuilder getSuspectMatrixOrBuilder(
        int index) {
      return suspectMatrix_.get(index);
    }
    
    private void initFields() {
      id_ = 0;
      gossipList_ = java.util.Collections.emptyList();
      suspectMatrix_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getGossipListCount(); i++) {
        if (!getGossipList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getSuspectMatrixCount(); i++) {
        if (!getSuspectMatrix(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      for (int i = 0; i < gossipList_.size(); i++) {
        output.writeMessage(2, gossipList_.get(i));
      }
      for (int i = 0; i < suspectMatrix_.size(); i++) {
        output.writeMessage(3, suspectMatrix_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      for (int i = 0; i < gossipList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, gossipList_.get(i));
      }
      for (int i = 0; i < suspectMatrix_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, suspectMatrix_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static gems.MetaDataProtos.MetaData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static gems.MetaDataProtos.MetaData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static gems.MetaDataProtos.MetaData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static gems.MetaDataProtos.MetaData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static gems.MetaDataProtos.MetaData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static gems.MetaDataProtos.MetaData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static gems.MetaDataProtos.MetaData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static gems.MetaDataProtos.MetaData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static gems.MetaDataProtos.MetaData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static gems.MetaDataProtos.MetaData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gems.MetaDataProtos.MetaData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gems.MetaDataProtos.MetaDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gems.MetaDataProtos.internal_static_tutorial_MetaData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gems.MetaDataProtos.internal_static_tutorial_MetaData_fieldAccessorTable;
      }
      
      // Construct using gems.MetaDataProtos.MetaData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGossipListFieldBuilder();
          getSuspectMatrixFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (gossipListBuilder_ == null) {
          gossipList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          gossipListBuilder_.clear();
        }
        if (suspectMatrixBuilder_ == null) {
          suspectMatrix_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          suspectMatrixBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gems.MetaDataProtos.MetaData.getDescriptor();
      }
      
      public gems.MetaDataProtos.MetaData getDefaultInstanceForType() {
        return gems.MetaDataProtos.MetaData.getDefaultInstance();
      }
      
      public gems.MetaDataProtos.MetaData build() {
        gems.MetaDataProtos.MetaData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private gems.MetaDataProtos.MetaData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        gems.MetaDataProtos.MetaData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public gems.MetaDataProtos.MetaData buildPartial() {
        gems.MetaDataProtos.MetaData result = new gems.MetaDataProtos.MetaData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (gossipListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            gossipList_ = java.util.Collections.unmodifiableList(gossipList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.gossipList_ = gossipList_;
        } else {
          result.gossipList_ = gossipListBuilder_.build();
        }
        if (suspectMatrixBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            suspectMatrix_ = java.util.Collections.unmodifiableList(suspectMatrix_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.suspectMatrix_ = suspectMatrix_;
        } else {
          result.suspectMatrix_ = suspectMatrixBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gems.MetaDataProtos.MetaData) {
          return mergeFrom((gems.MetaDataProtos.MetaData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(gems.MetaDataProtos.MetaData other) {
        if (other == gems.MetaDataProtos.MetaData.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (gossipListBuilder_ == null) {
          if (!other.gossipList_.isEmpty()) {
            if (gossipList_.isEmpty()) {
              gossipList_ = other.gossipList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureGossipListIsMutable();
              gossipList_.addAll(other.gossipList_);
            }
            onChanged();
          }
        } else {
          if (!other.gossipList_.isEmpty()) {
            if (gossipListBuilder_.isEmpty()) {
              gossipListBuilder_.dispose();
              gossipListBuilder_ = null;
              gossipList_ = other.gossipList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              gossipListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getGossipListFieldBuilder() : null;
            } else {
              gossipListBuilder_.addAllMessages(other.gossipList_);
            }
          }
        }
        if (suspectMatrixBuilder_ == null) {
          if (!other.suspectMatrix_.isEmpty()) {
            if (suspectMatrix_.isEmpty()) {
              suspectMatrix_ = other.suspectMatrix_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureSuspectMatrixIsMutable();
              suspectMatrix_.addAll(other.suspectMatrix_);
            }
            onChanged();
          }
        } else {
          if (!other.suspectMatrix_.isEmpty()) {
            if (suspectMatrixBuilder_.isEmpty()) {
              suspectMatrixBuilder_.dispose();
              suspectMatrixBuilder_ = null;
              suspectMatrix_ = other.suspectMatrix_;
              bitField0_ = (bitField0_ & ~0x00000004);
              suspectMatrixBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSuspectMatrixFieldBuilder() : null;
            } else {
              suspectMatrixBuilder_.addAllMessages(other.suspectMatrix_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getGossipListCount(); i++) {
          if (!getGossipList(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getSuspectMatrixCount(); i++) {
          if (!getSuspectMatrix(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              gems.MetaDataProtos.MetaData.GossipEntry.Builder subBuilder = gems.MetaDataProtos.MetaData.GossipEntry.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addGossipList(subBuilder.buildPartial());
              break;
            }
            case 26: {
              gems.MetaDataProtos.MetaData.SuspectEntry.Builder subBuilder = gems.MetaDataProtos.MetaData.SuspectEntry.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSuspectMatrix(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .tutorial.MetaData.GossipEntry GossipList = 2;
      private java.util.List<gems.MetaDataProtos.MetaData.GossipEntry> gossipList_ =
        java.util.Collections.emptyList();
      private void ensureGossipListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          gossipList_ = new java.util.ArrayList<gems.MetaDataProtos.MetaData.GossipEntry>(gossipList_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          gems.MetaDataProtos.MetaData.GossipEntry, gems.MetaDataProtos.MetaData.GossipEntry.Builder, gems.MetaDataProtos.MetaData.GossipEntryOrBuilder> gossipListBuilder_;
      
      public java.util.List<gems.MetaDataProtos.MetaData.GossipEntry> getGossipListList() {
        if (gossipListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(gossipList_);
        } else {
          return gossipListBuilder_.getMessageList();
        }
      }
      public int getGossipListCount() {
        if (gossipListBuilder_ == null) {
          return gossipList_.size();
        } else {
          return gossipListBuilder_.getCount();
        }
      }
      public gems.MetaDataProtos.MetaData.GossipEntry getGossipList(int index) {
        if (gossipListBuilder_ == null) {
          return gossipList_.get(index);
        } else {
          return gossipListBuilder_.getMessage(index);
        }
      }
      public Builder setGossipList(
          int index, gems.MetaDataProtos.MetaData.GossipEntry value) {
        if (gossipListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGossipListIsMutable();
          gossipList_.set(index, value);
          onChanged();
        } else {
          gossipListBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setGossipList(
          int index, gems.MetaDataProtos.MetaData.GossipEntry.Builder builderForValue) {
        if (gossipListBuilder_ == null) {
          ensureGossipListIsMutable();
          gossipList_.set(index, builderForValue.build());
          onChanged();
        } else {
          gossipListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addGossipList(gems.MetaDataProtos.MetaData.GossipEntry value) {
        if (gossipListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGossipListIsMutable();
          gossipList_.add(value);
          onChanged();
        } else {
          gossipListBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addGossipList(
          int index, gems.MetaDataProtos.MetaData.GossipEntry value) {
        if (gossipListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGossipListIsMutable();
          gossipList_.add(index, value);
          onChanged();
        } else {
          gossipListBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addGossipList(
          gems.MetaDataProtos.MetaData.GossipEntry.Builder builderForValue) {
        if (gossipListBuilder_ == null) {
          ensureGossipListIsMutable();
          gossipList_.add(builderForValue.build());
          onChanged();
        } else {
          gossipListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addGossipList(
          int index, gems.MetaDataProtos.MetaData.GossipEntry.Builder builderForValue) {
        if (gossipListBuilder_ == null) {
          ensureGossipListIsMutable();
          gossipList_.add(index, builderForValue.build());
          onChanged();
        } else {
          gossipListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllGossipList(
          java.lang.Iterable<? extends gems.MetaDataProtos.MetaData.GossipEntry> values) {
        if (gossipListBuilder_ == null) {
          ensureGossipListIsMutable();
          super.addAll(values, gossipList_);
          onChanged();
        } else {
          gossipListBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearGossipList() {
        if (gossipListBuilder_ == null) {
          gossipList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          gossipListBuilder_.clear();
        }
        return this;
      }
      public Builder removeGossipList(int index) {
        if (gossipListBuilder_ == null) {
          ensureGossipListIsMutable();
          gossipList_.remove(index);
          onChanged();
        } else {
          gossipListBuilder_.remove(index);
        }
        return this;
      }
      public gems.MetaDataProtos.MetaData.GossipEntry.Builder getGossipListBuilder(
          int index) {
        return getGossipListFieldBuilder().getBuilder(index);
      }
      public gems.MetaDataProtos.MetaData.GossipEntryOrBuilder getGossipListOrBuilder(
          int index) {
        if (gossipListBuilder_ == null) {
          return gossipList_.get(index);  } else {
          return gossipListBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends gems.MetaDataProtos.MetaData.GossipEntryOrBuilder> 
           getGossipListOrBuilderList() {
        if (gossipListBuilder_ != null) {
          return gossipListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(gossipList_);
        }
      }
      public gems.MetaDataProtos.MetaData.GossipEntry.Builder addGossipListBuilder() {
        return getGossipListFieldBuilder().addBuilder(
            gems.MetaDataProtos.MetaData.GossipEntry.getDefaultInstance());
      }
      public gems.MetaDataProtos.MetaData.GossipEntry.Builder addGossipListBuilder(
          int index) {
        return getGossipListFieldBuilder().addBuilder(
            index, gems.MetaDataProtos.MetaData.GossipEntry.getDefaultInstance());
      }
      public java.util.List<gems.MetaDataProtos.MetaData.GossipEntry.Builder> 
           getGossipListBuilderList() {
        return getGossipListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          gems.MetaDataProtos.MetaData.GossipEntry, gems.MetaDataProtos.MetaData.GossipEntry.Builder, gems.MetaDataProtos.MetaData.GossipEntryOrBuilder> 
          getGossipListFieldBuilder() {
        if (gossipListBuilder_ == null) {
          gossipListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              gems.MetaDataProtos.MetaData.GossipEntry, gems.MetaDataProtos.MetaData.GossipEntry.Builder, gems.MetaDataProtos.MetaData.GossipEntryOrBuilder>(
                  gossipList_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          gossipList_ = null;
        }
        return gossipListBuilder_;
      }
      
      // repeated .tutorial.MetaData.SuspectEntry SuspectMatrix = 3;
      private java.util.List<gems.MetaDataProtos.MetaData.SuspectEntry> suspectMatrix_ =
        java.util.Collections.emptyList();
      private void ensureSuspectMatrixIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          suspectMatrix_ = new java.util.ArrayList<gems.MetaDataProtos.MetaData.SuspectEntry>(suspectMatrix_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          gems.MetaDataProtos.MetaData.SuspectEntry, gems.MetaDataProtos.MetaData.SuspectEntry.Builder, gems.MetaDataProtos.MetaData.SuspectEntryOrBuilder> suspectMatrixBuilder_;
      
      public java.util.List<gems.MetaDataProtos.MetaData.SuspectEntry> getSuspectMatrixList() {
        if (suspectMatrixBuilder_ == null) {
          return java.util.Collections.unmodifiableList(suspectMatrix_);
        } else {
          return suspectMatrixBuilder_.getMessageList();
        }
      }
      public int getSuspectMatrixCount() {
        if (suspectMatrixBuilder_ == null) {
          return suspectMatrix_.size();
        } else {
          return suspectMatrixBuilder_.getCount();
        }
      }
      public gems.MetaDataProtos.MetaData.SuspectEntry getSuspectMatrix(int index) {
        if (suspectMatrixBuilder_ == null) {
          return suspectMatrix_.get(index);
        } else {
          return suspectMatrixBuilder_.getMessage(index);
        }
      }
      public Builder setSuspectMatrix(
          int index, gems.MetaDataProtos.MetaData.SuspectEntry value) {
        if (suspectMatrixBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSuspectMatrixIsMutable();
          suspectMatrix_.set(index, value);
          onChanged();
        } else {
          suspectMatrixBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setSuspectMatrix(
          int index, gems.MetaDataProtos.MetaData.SuspectEntry.Builder builderForValue) {
        if (suspectMatrixBuilder_ == null) {
          ensureSuspectMatrixIsMutable();
          suspectMatrix_.set(index, builderForValue.build());
          onChanged();
        } else {
          suspectMatrixBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addSuspectMatrix(gems.MetaDataProtos.MetaData.SuspectEntry value) {
        if (suspectMatrixBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSuspectMatrixIsMutable();
          suspectMatrix_.add(value);
          onChanged();
        } else {
          suspectMatrixBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addSuspectMatrix(
          int index, gems.MetaDataProtos.MetaData.SuspectEntry value) {
        if (suspectMatrixBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSuspectMatrixIsMutable();
          suspectMatrix_.add(index, value);
          onChanged();
        } else {
          suspectMatrixBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addSuspectMatrix(
          gems.MetaDataProtos.MetaData.SuspectEntry.Builder builderForValue) {
        if (suspectMatrixBuilder_ == null) {
          ensureSuspectMatrixIsMutable();
          suspectMatrix_.add(builderForValue.build());
          onChanged();
        } else {
          suspectMatrixBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addSuspectMatrix(
          int index, gems.MetaDataProtos.MetaData.SuspectEntry.Builder builderForValue) {
        if (suspectMatrixBuilder_ == null) {
          ensureSuspectMatrixIsMutable();
          suspectMatrix_.add(index, builderForValue.build());
          onChanged();
        } else {
          suspectMatrixBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllSuspectMatrix(
          java.lang.Iterable<? extends gems.MetaDataProtos.MetaData.SuspectEntry> values) {
        if (suspectMatrixBuilder_ == null) {
          ensureSuspectMatrixIsMutable();
          super.addAll(values, suspectMatrix_);
          onChanged();
        } else {
          suspectMatrixBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearSuspectMatrix() {
        if (suspectMatrixBuilder_ == null) {
          suspectMatrix_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          suspectMatrixBuilder_.clear();
        }
        return this;
      }
      public Builder removeSuspectMatrix(int index) {
        if (suspectMatrixBuilder_ == null) {
          ensureSuspectMatrixIsMutable();
          suspectMatrix_.remove(index);
          onChanged();
        } else {
          suspectMatrixBuilder_.remove(index);
        }
        return this;
      }
      public gems.MetaDataProtos.MetaData.SuspectEntry.Builder getSuspectMatrixBuilder(
          int index) {
        return getSuspectMatrixFieldBuilder().getBuilder(index);
      }
      public gems.MetaDataProtos.MetaData.SuspectEntryOrBuilder getSuspectMatrixOrBuilder(
          int index) {
        if (suspectMatrixBuilder_ == null) {
          return suspectMatrix_.get(index);  } else {
          return suspectMatrixBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends gems.MetaDataProtos.MetaData.SuspectEntryOrBuilder> 
           getSuspectMatrixOrBuilderList() {
        if (suspectMatrixBuilder_ != null) {
          return suspectMatrixBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(suspectMatrix_);
        }
      }
      public gems.MetaDataProtos.MetaData.SuspectEntry.Builder addSuspectMatrixBuilder() {
        return getSuspectMatrixFieldBuilder().addBuilder(
            gems.MetaDataProtos.MetaData.SuspectEntry.getDefaultInstance());
      }
      public gems.MetaDataProtos.MetaData.SuspectEntry.Builder addSuspectMatrixBuilder(
          int index) {
        return getSuspectMatrixFieldBuilder().addBuilder(
            index, gems.MetaDataProtos.MetaData.SuspectEntry.getDefaultInstance());
      }
      public java.util.List<gems.MetaDataProtos.MetaData.SuspectEntry.Builder> 
           getSuspectMatrixBuilderList() {
        return getSuspectMatrixFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          gems.MetaDataProtos.MetaData.SuspectEntry, gems.MetaDataProtos.MetaData.SuspectEntry.Builder, gems.MetaDataProtos.MetaData.SuspectEntryOrBuilder> 
          getSuspectMatrixFieldBuilder() {
        if (suspectMatrixBuilder_ == null) {
          suspectMatrixBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              gems.MetaDataProtos.MetaData.SuspectEntry, gems.MetaDataProtos.MetaData.SuspectEntry.Builder, gems.MetaDataProtos.MetaData.SuspectEntryOrBuilder>(
                  suspectMatrix_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          suspectMatrix_ = null;
        }
        return suspectMatrixBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:tutorial.MetaData)
    }
    
    static {
      defaultInstance = new MetaData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tutorial.MetaData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_MetaData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_MetaData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_MetaData_GossipEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_MetaData_GossipEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_MetaData_SuspectEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_MetaData_SuspectEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_MetaData_SuspectEntry_SuspectRowEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_MetaData_SuspectEntry_SuspectRowEntry_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023gems/metadata.proto\022\010tutorial\"\314\002\n\010Meta" +
      "Data\022\n\n\002id\030\001 \002(\005\0222\n\nGossipList\030\002 \003(\0132\036.t" +
      "utorial.MetaData.GossipEntry\0226\n\rSuspectM" +
      "atrix\030\003 \003(\0132\037.tutorial.MetaData.SuspectE" +
      "ntry\032,\n\013GossipEntry\022\n\n\002id\030\001 \002(\005\022\021\n\theart" +
      "beat\030\002 \002(\005\032\231\001\n\014SuspectEntry\022\020\n\010rowIndex\030" +
      "\001 \002(\005\022C\n\nSuspectRow\030\002 \003(\0132/.tutorial.Met" +
      "aData.SuspectEntry.SuspectRowEntry\0322\n\017Su" +
      "spectRowEntry\022\020\n\010colindex\030\001 \002(\005\022\r\n\005value" +
      "\030\002 \002(\005B\026\n\004gemsB\016MetaDataProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_MetaData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_MetaData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_MetaData_descriptor,
              new java.lang.String[] { "Id", "GossipList", "SuspectMatrix", },
              gems.MetaDataProtos.MetaData.class,
              gems.MetaDataProtos.MetaData.Builder.class);
          internal_static_tutorial_MetaData_GossipEntry_descriptor =
            internal_static_tutorial_MetaData_descriptor.getNestedTypes().get(0);
          internal_static_tutorial_MetaData_GossipEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_MetaData_GossipEntry_descriptor,
              new java.lang.String[] { "Id", "Heartbeat", },
              gems.MetaDataProtos.MetaData.GossipEntry.class,
              gems.MetaDataProtos.MetaData.GossipEntry.Builder.class);
          internal_static_tutorial_MetaData_SuspectEntry_descriptor =
            internal_static_tutorial_MetaData_descriptor.getNestedTypes().get(1);
          internal_static_tutorial_MetaData_SuspectEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_MetaData_SuspectEntry_descriptor,
              new java.lang.String[] { "RowIndex", "SuspectRow", },
              gems.MetaDataProtos.MetaData.SuspectEntry.class,
              gems.MetaDataProtos.MetaData.SuspectEntry.Builder.class);
          internal_static_tutorial_MetaData_SuspectEntry_SuspectRowEntry_descriptor =
            internal_static_tutorial_MetaData_SuspectEntry_descriptor.getNestedTypes().get(0);
          internal_static_tutorial_MetaData_SuspectEntry_SuspectRowEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_MetaData_SuspectEntry_SuspectRowEntry_descriptor,
              new java.lang.String[] { "Colindex", "Value", },
              gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.class,
              gems.MetaDataProtos.MetaData.SuspectEntry.SuspectRowEntry.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
